server:
  port: 9000

spring:
  application:
    name: jrunmall-order
  datasource:
    username: ${JRUNMALL_MYSQL_USERNAME:${GULIMALL_MYSQL_USERNAME:root}}
    password: ${JRUNMALL_MYSQL_PASSWORD:${GULIMALL_MYSQL_PASSWORD:root}}
    url: jdbc:mysql://${JRUNMALL_MYSQL_HOST:${GULIMALL_MYSQL_HOST:127.0.0.1}}:${JRUNMALL_MYSQL_PORT:${GULIMALL_MYSQL_PORT:3306}}/${JRUNMALL_ORDER_MYSQL_DATABASE:${GULIMALL_ORDER_MYSQL_DATABASE:jrunmall_commerce}}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: ${JRUNMALL_NACOS_ADDR:${GULIMALL_NACOS_ADDR:127.0.0.1:8848}}

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: ${JRUNMALL_SENTINEL_DASHBOARD:${GULIMALL_SENTINEL_DASHBOARD:127.0.0.1:8858}}

  redis:
    host: ${JRUNMALL_REDIS_HOST:${GULIMALL_REDIS_HOST:127.0.0.1}}
    port: ${JRUNMALL_REDIS_PORT:${GULIMALL_REDIS_PORT:6379}}

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #\u8BBE\u7F6E\u5B9E\u4F53\u7C7B\u7684\u81EA\u589E\u4E3B\u952E
  global-config:
    db-config:
      id-type: auto



#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'








